export const COUNTRY_CODES = [
    { code: 'AU', dial: '+61', flag: '🇦🇺', label: 'Australia' },
    { code: 'US', dial: '+1', flag: '🇺🇸', label: 'United States' },
    { code: 'GB', dial: '+44', flag: '🇬🇧', label: 'United Kingdom' },
    { code: 'CA', dial: '+1', flag: '🇨🇦', label: 'Canada' },
    { code: 'ID', dial: '+62', flag: '🇮🇩', label: 'Indonesia' },
    { code: 'SG', dial: '+65', flag: '🇸🇬', label: 'Singapore' },
    { code: 'MY', dial: '+60', flag: '🇲🇾', label: 'Malaysia' },
    { code: 'NZ', dial: '+64', flag: '🇳🇿', label: 'New Zealand' },
    { code: 'PH', dial: '+63', flag: '🇵🇭', label: 'Philippines' },
    { code: 'TH', dial: '+66', flag: '🇹🇭', label: 'Thailand' },
    { code: 'VN', dial: '+84', flag: '🇻🇳', label: 'Vietnam' },
    { code: 'IN', dial: '+91', flag: '🇮🇳', label: 'India' },
    { code: 'CN', dial: '+86', flag: '🇨🇳', label: 'China' },
    { code: 'JP', dial: '+81', flag: '🇯🇵', label: 'Japan' },
    { code: 'KR', dial: '+82', flag: '🇰🇷', label: 'South Korea' },
    { code: 'HK', dial: '+852', flag: '🇭🇰', label: 'Hong Kong' },
    { code: 'TW', dial: '+886', flag: '🇹🇼', label: 'Taiwan' },
    { code: 'AE', dial: '+971', flag: '🇦🇪', label: 'United Arab Emirates' },
    { code: 'SA', dial: '+966', flag: '🇸🇦', label: 'Saudi Arabia' },
    { code: 'IL', dial: '+972', flag: '🇮🇱', label: 'Israel' },
    { code: 'TR', dial: '+90', flag: '🇹🇷', label: 'Turkey' },
    { code: 'DE', dial: '+49', flag: '🇩🇪', label: 'Germany' },
    { code: 'FR', dial: '+33', flag: '🇫🇷', label: 'France' },
    { code: 'IT', dial: '+39', flag: '🇮🇹', label: 'Italy' },
    { code: 'ES', dial: '+34', flag: '🇪🇸', label: 'Spain' },
    { code: 'NL', dial: '+31', flag: '🇳🇱', label: 'Netherlands' },
    { code: 'BE', dial: '+32', flag: '🇧🇪', label: 'Belgium' },
    { code: 'CH', dial: '+41', flag: '🇨🇭', label: 'Switzerland' },
    { code: 'AT', dial: '+43', flag: '🇦🇹', label: 'Austria' },
    { code: 'SE', dial: '+46', flag: '🇸🇪', label: 'Sweden' },
    { code: 'NO', dial: '+47', flag: '🇳🇴', label: 'Norway' },
    { code: 'DK', dial: '+45', flag: '🇩🇰', label: 'Denmark' },
    { code: 'FI', dial: '+358', flag: '🇫🇮', label: 'Finland' },
    { code: 'PL', dial: '+48', flag: '🇵🇱', label: 'Poland' },
    { code: 'CZ', dial: '+420', flag: '🇨🇿', label: 'Czech Republic' },
    { code: 'PT', dial: '+351', flag: '🇵🇹', label: 'Portugal' },
    { code: 'GR', dial: '+30', flag: '🇬🇷', label: 'Greece' },
    { code: 'RU', dial: '+7', flag: '🇷🇺', label: 'Russia' },
    { code: 'BR', dial: '+55', flag: '🇧🇷', label: 'Brazil' },
    { code: 'MX', dial: '+52', flag: '🇲🇽', label: 'Mexico' },
    { code: 'AR', dial: '+54', flag: '🇦🇷', label: 'Argentina' },
    { code: 'CL', dial: '+56', flag: '🇨🇱', label: 'Chile' },
    { code: 'CO', dial: '+57', flag: '🇨🇴', label: 'Colombia' },
    { code: 'PE', dial: '+51', flag: '🇵🇪', label: 'Peru' },
    { code: 'ZA', dial: '+27', flag: '🇿🇦', label: 'South Africa' },
    { code: 'EG', dial: '+20', flag: '🇪🇬', label: 'Egypt' },
    { code: 'NG', dial: '+234', flag: '🇳🇬', label: 'Nigeria' },
    { code: 'KE', dial: '+254', flag: '🇰🇪', label: 'Kenya' },
    { code: 'IE', dial: '+353', flag: '🇮🇪', label: 'Ireland' },
    { code: 'PK', dial: '+92', flag: '🇵🇰', label: 'Pakistan' },
    { code: 'BD', dial: '+880', flag: '🇧🇩', label: 'Bangladesh' },
    { code: 'LK', dial: '+94', flag: '🇱🇰', label: 'Sri Lanka' },
    { code: 'NP', dial: '+977', flag: '🇳🇵', label: 'Nepal' },
    { code: 'AF', dial: '+93', flag: '🇦🇫', label: 'Afghanistan' },
    { code: 'MM', dial: '+95', flag: '🇲🇲', label: 'Myanmar' },
    { code: 'KH', dial: '+855', flag: '🇰🇭', label: 'Cambodia' },
    { code: 'LA', dial: '+856', flag: '🇱🇦', label: 'Laos' },
    { code: 'BN', dial: '+673', flag: '🇧🇳', label: 'Brunei' },
    { code: 'MV', dial: '+960', flag: '🇲🇻', label: 'Maldives' },
    { code: 'FJ', dial: '+679', flag: '🇫🇯', label: 'Fiji' },
    { code: 'PG', dial: '+675', flag: '🇵🇬', label: 'Papua New Guinea' },
];
