export const COUNTRY_CODES = [
    { code: 'AF', label: 'Afghanistan', dial: '+93', flag: '🇦🇫' },
    { code: 'AX', label: 'Åland Islands', dial: '+358', flag: '🇦🇽' },
    { code: 'AL', label: 'Albania', dial: '+355', flag: '🇦🇱' },
    { code: 'DZ', label: 'Algeria', dial: '+213', flag: '🇩🇿' },
    { code: 'AS', label: 'American Samoa', dial: '+1684', flag: '🇦🇸' },
    { code: 'AD', label: 'Andorra', dial: '+376', flag: '🇦🇩' },
    { code: 'AO', label: 'Angola', dial: '+244', flag: '🇦🇴' },
    { code: 'AI', label: 'Anguilla', dial: '+1264', flag: '🇦🇮' },
    { code: 'AQ', label: 'Antarctica', dial: '+672', flag: '🇦🇶' },
    { code: 'AG', label: 'Antigua and Barbuda', dial: '+1268', flag: '🇦🇬' },
    { code: 'AR', label: 'Argentina', dial: '+54', flag: '🇦🇷' },
    { code: 'AM', label: 'Armenia', dial: '+374', flag: '🇦🇲' },
    { code: 'AW', label: 'Aruba', dial: '+297', flag: '🇦🇼' },
    { code: 'AU', label: 'Australia', dial: '+61', flag: '🇦🇺' },
    { code: 'AT', label: 'Austria', dial: '+43', flag: '🇦🇹' },
    { code: 'AZ', label: 'Azerbaijan', dial: '+994', flag: '🇦🇿' },
    { code: 'BS', label: 'Bahamas', dial: '+1242', flag: '🇧🇸' },
    { code: 'BH', label: 'Bahrain', dial: '+973', flag: '🇧🇭' },
    { code: 'BD', label: 'Bangladesh', dial: '+880', flag: '🇧🇩' },
    { code: 'BB', label: 'Barbados', dial: '+1246', flag: '🇧🇧' },
    { code: 'BY', label: 'Belarus', dial: '+375', flag: '🇧🇾' },
    { code: 'BE', label: 'Belgium', dial: '+32', flag: '🇧🇪' },
    { code: 'BZ', label: 'Belize', dial: '+501', flag: '🇧🇿' },
    { code: 'BJ', label: 'Benin', dial: '+229', flag: '🇧🇯' },
    { code: 'BM', label: 'Bermuda', dial: '+1441', flag: '🇧🇲' },
    { code: 'BT', label: 'Bhutan', dial: '+975', flag: '🇧🇹' },
    { code: 'BO', label: 'Bolivia', dial: '+591', flag: '🇧🇴' },
    { code: 'BA', label: 'Bosnia and Herzegovina', dial: '+387', flag: '🇧🇦' },
    { code: 'BW', label: 'Botswana', dial: '+267', flag: '🇧🇼' },
    { code: 'BV', label: 'Bouvet Island', dial: '+47', flag: '🇧🇻' },
    { code: 'BR', label: 'Brazil', dial: '+55', flag: '🇧🇷' },
    { code: 'IO', label: 'British Indian Ocean Territory', dial: '+246', flag: '🇮🇴' },
    { code: 'BN', label: 'Brunei Darussalam', dial: '+673', flag: '🇧🇳' },
    { code: 'BG', label: 'Bulgaria', dial: '+359', flag: '🇧🇬' },
    { code: 'BF', label: 'Burkina Faso', dial: '+226', flag: '🇧🇫' },
    { code: 'BI', label: 'Burundi', dial: '+257', flag: '🇧🇮' },
    { code: 'KH', label: 'Cambodia', dial: '+855', flag: '🇰🇭' },
    { code: 'CM', label: 'Cameroon', dial: '+237', flag: '🇨🇲' },
    { code: 'CA', label: 'Canada', dial: '+1', flag: '🇨🇦' },
    { code: 'CV', label: 'Cape Verde', dial: '+238', flag: '🇨🇻' },
    { code: 'KY', label: 'Cayman Islands', dial: '+1345', flag: '🇰🇾' },
    { code: 'CF', label: 'Central African Republic', dial: '+236', flag: '🇨🇫' },
    { code: 'TD', label: 'Chad', dial: '+235', flag: '🇹🇩' },
    { code: 'CL', label: 'Chile', dial: '+56', flag: '🇨🇱' },
    { code: 'CN', label: 'China', dial: '+86', flag: '🇨🇳' },
    { code: 'CX', label: 'Christmas Island', dial: '+61', flag: '🇨🇽' },
    { code: 'CC', label: 'Cocos (Keeling) Islands', dial: '+61', flag: '🇨🇨' },
    { code: 'CO', label: 'Colombia', dial: '+57', flag: '🇨🇴' },
    { code: 'KM', label: 'Comoros', dial: '+269', flag: '🇰🇲' },
    { code: 'CG', label: 'Congo', dial: '+242', flag: '🇨🇬' },
    { code: 'CD', label: 'Congo, Democratic Republic', dial: '+243', flag: '🇨🇩' },
    { code: 'CK', label: 'Cook Islands', dial: '+682', flag: '🇨🇰' },
    { code: 'CR', label: 'Costa Rica', dial: '+506', flag: '🇨🇷' },
    { code: 'CI', label: 'Côte d\'Ivoire', dial: '+225', flag: '🇨🇮' },
    { code: 'HR', label: 'Croatia', dial: '+385', flag: '🇭🇷' },
    { code: 'CU', label: 'Cuba', dial: '+53', flag: '🇨🇺' },
    { code: 'CW', label: 'Curaçao', dial: '+599', flag: '🇨🇼' },
    { code: 'CY', label: 'Cyprus', dial: '+357', flag: '🇨🇾' },
    { code: 'CZ', label: 'Czech Republic', dial: '+420', flag: '🇨🇿' },
    { code: 'DK', label: 'Denmark', dial: '+45', flag: '🇩🇰' },
    { code: 'DJ', label: 'Djibouti', dial: '+253', flag: '🇩🇯' },
    { code: 'DM', label: 'Dominica', dial: '+1767', flag: '🇩🇲' },
    { code: 'DO', label: 'Dominican Republic', dial: '+1809', flag: '🇩🇴' },
    { code: 'EC', label: 'Ecuador', dial: '+593', flag: '🇪🇨' },
    { code: 'EG', label: 'Egypt', dial: '+20', flag: '🇪🇬' },
    { code: 'SV', label: 'El Salvador', dial: '+503', flag: '🇸🇻' },
    { code: 'GQ', label: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶' },
    { code: 'ER', label: 'Eritrea', dial: '+291', flag: '🇪🇷' },
    { code: 'EE', label: 'Estonia', dial: '+372', flag: '🇪🇪' },
    { code: 'ET', label: 'Ethiopia', dial: '+251', flag: '🇪🇹' },
    { code: 'FK', label: 'Falkland Islands', dial: '+500', flag: '🇫🇰' },
    { code: 'FO', label: 'Faroe Islands', dial: '+298', flag: '🇫🇴' },
    { code: 'FJ', label: 'Fiji', dial: '+679', flag: '🇫🇯' },
    { code: 'FI', label: 'Finland', dial: '+358', flag: '🇫🇮' },
    { code: 'FR', label: 'France', dial: '+33', flag: '🇫🇷' },
    { code: 'GF', label: 'French Guiana', dial: '+594', flag: '🇬🇫' },
    { code: 'PF', label: 'French Polynesia', dial: '+689', flag: '🇵🇫' },
    { code: 'TF', label: 'French Southern Territories', dial: '+262', flag: '🇹🇫' },
    { code: 'GA', label: 'Gabon', dial: '+241', flag: '🇬🇦' },
    { code: 'GM', label: 'Gambia', dial: '+220', flag: '🇬🇲' },
    { code: 'GE', label: 'Georgia', dial: '+995', flag: '🇬🇪' },
    { code: 'DE', label: 'Germany', dial: '+49', flag: '🇩🇪' },
    { code: 'GH', label: 'Ghana', dial: '+233', flag: '🇬🇭' },
    { code: 'GI', label: 'Gibraltar', dial: '+350', flag: '🇬🇮' },
    { code: 'GR', label: 'Greece', dial: '+30', flag: '🇬🇷' },
    { code: 'GL', label: 'Greenland', dial: '+299', flag: '🇬🇱' },
    { code: 'GD', label: 'Grenada', dial: '+1473', flag: '🇬🇩' },
    { code: 'GP', label: 'Guadeloupe', dial: '+590', flag: '🇬🇵' },
    { code: 'GU', label: 'Guam', dial: '+1671', flag: '🇬🇺' },
    { code: 'GT', label: 'Guatemala', dial: '+502', flag: '🇬🇹' },
    { code: 'GG', label: 'Guernsey', dial: '+44', flag: '🇬🇬' },
    { code: 'GN', label: 'Guinea', dial: '+224', flag: '🇬🇳' },
    { code: 'GW', label: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼' },
    { code: 'GY', label: 'Guyana', dial: '+592', flag: '🇬🇾' },
    { code: 'HT', label: 'Haiti', dial: '+509', flag: '🇭🇹' },
    { code: 'HM', label: 'Heard Island and McDonald Islands', dial: '+672', flag: '🇭🇲' },
    { code: 'VA', label: 'Holy See (Vatican City State)', dial: '+379', flag: '🇻🇦' },
    { code: 'HN', label: 'Honduras', dial: '+504', flag: '🇭🇳' },
    { code: 'HK', label: 'Hong Kong', dial: '+852', flag: '🇭🇰' },
    { code: 'HU', label: 'Hungary', dial: '+36', flag: '🇭🇺' },
    { code: 'IS', label: 'Iceland', dial: '+354', flag: '🇮🇸' },
    { code: 'IN', label: 'India', dial: '+91', flag: '🇮🇳' },
    { code: 'ID', label: 'Indonesia', dial: '+62', flag: '🇮🇩' },
    { code: 'IR', label: 'Iran', dial: '+98', flag: '🇮🇷' },
    { code: 'IQ', label: 'Iraq', dial: '+964', flag: '🇮🇶' },
    { code: 'IE', label: 'Ireland', dial: '+353', flag: '🇮🇪' },
    { code: 'IM', label: 'Isle of Man', dial: '+44', flag: '🇮🇲' },
    { code: 'IL', label: 'Israel', dial: '+972', flag: '🇮🇱' },
    { code: 'IT', label: 'Italy', dial: '+39', flag: '🇮🇹' },
    { code: 'JM', label: 'Jamaica', dial: '+1876', flag: '🇯🇲' },
    { code: 'JP', label: 'Japan', dial: '+81', flag: '🇯🇵' },
    { code: 'JE', label: 'Jersey', dial: '+44', flag: '🇯🇪' },
    { code: 'JO', label: 'Jordan', dial: '+962', flag: '🇯🇴' },
    { code: 'KZ', label: 'Kazakhstan', dial: '+7', flag: '🇰🇿' },
    { code: 'KE', label: 'Kenya', dial: '+254', flag: '🇰🇪' },
    { code: 'KI', label: 'Kiribati', dial: '+686', flag: '🇰🇮' },
    { code: 'KP', label: 'Korea, Democratic People\'s Republic', dial: '+850', flag: '🇰🇵' },
    { code: 'KR', label: 'Korea, Republic of', dial: '+82', flag: '🇰🇷' },
    { code: 'KW', label: 'Kuwait', dial: '+965', flag: '🇰🇼' },
    { code: 'KG', label: 'Kyrgyzstan', dial: '+996', flag: '🇰🇬' },
    { code: 'LA', label: 'Lao People\'s Democratic Republic', dial: '+856', flag: '🇱🇦' },
    { code: 'LV', label: 'Latvia', dial: '+371', flag: '🇱🇻' },
    { code: 'LB', label: 'Lebanon', dial: '+961', flag: '🇱🇧' },
    { code: 'LS', label: 'Lesotho', dial: '+266', flag: '🇱🇸' },
    { code: 'LR', label: 'Liberia', dial: '+231', flag: '🇱🇷' },
    { code: 'LY', label: 'Libya', dial: '+218', flag: '🇱🇾' },
    { code: 'LI', label: 'Liechtenstein', dial: '+423', flag: '🇱🇮' },
    { code: 'LT', label: 'Lithuania', dial: '+370', flag: '🇱🇹' },
    { code: 'LU', label: 'Luxembourg', dial: '+352', flag: '🇱🇺' },
    { code: 'MO', label: 'Macao', dial: '+853', flag: '🇲🇴' },
    { code: 'MK', label: 'Macedonia', dial: '+389', flag: '🇲🇰' },
    { code: 'MG', label: 'Madagascar', dial: '+261', flag: '🇲🇬' },
    { code: 'MW', label: 'Malawi', dial: '+265', flag: '🇲🇼' },
    { code: 'MY', label: 'Malaysia', dial: '+60', flag: '🇲🇾' },
    { code: 'MV', label: 'Maldives', dial: '+960', flag: '🇲🇻' },
    { code: 'ML', label: 'Mali', dial: '+223', flag: '🇲🇱' },
    { code: 'MT', label: 'Malta', dial: '+356', flag: '🇲🇹' },
    { code: 'MH', label: 'Marshall Islands', dial: '+692', flag: '🇲🇭' },
    { code: 'MQ', label: 'Martinique', dial: '+596', flag: '🇲🇶' },
    { code: 'MR', label: 'Mauritania', dial: '+222', flag: '🇲🇷' },
    { code: 'MU', label: 'Mauritius', dial: '+230', flag: '🇲🇺' },
    { code: 'YT', label: 'Mayotte', dial: '+262', flag: '🇾🇹' },
    { code: 'MX', label: 'Mexico', dial: '+52', flag: '🇲🇽' },
    { code: 'FM', label: 'Micronesia', dial: '+691', flag: '🇫🇲' },
    { code: 'MD', label: 'Moldova', dial: '+373', flag: '🇲🇩' },
    { code: 'MC', label: 'Monaco', dial: '+377', flag: '🇲🇨' },
    { code: 'MN', label: 'Mongolia', dial: '+976', flag: '🇲🇳' },
    { code: 'ME', label: 'Montenegro', dial: '+382', flag: '🇲🇪' },
    { code: 'MS', label: 'Montserrat', dial: '+1664', flag: '🇲🇸' },
    { code: 'MA', label: 'Morocco', dial: '+212', flag: '🇲🇦' },
    { code: 'MZ', label: 'Mozambique', dial: '+258', flag: '🇲🇿' },
    { code: 'MM', label: 'Myanmar', dial: '+95', flag: '🇲🇲' },
    { code: 'NA', label: 'Namibia', dial: '+264', flag: '🇳🇦' },
    { code: 'NR', label: 'Nauru', dial: '+674', flag: '🇳🇷' },
    { code: 'NP', label: 'Nepal', dial: '+977', flag: '🇳🇵' },
    { code: 'NL', label: 'Netherlands', dial: '+31', flag: '🇳🇱' },
    { code: 'NC', label: 'New Caledonia', dial: '+687', flag: '🇳🇨' },
    { code: 'NZ', label: 'New Zealand', dial: '+64', flag: '🇳🇿' },
    { code: 'NI', label: 'Nicaragua', dial: '+505', flag: '🇳🇮' },
    { code: 'NE', label: 'Niger', dial: '+227', flag: '🇳🇪' },
    { code: 'NG', label: 'Nigeria', dial: '+234', flag: '🇳🇬' },
    { code: 'NU', label: 'Niue', dial: '+683', flag: '🇳🇺' },
    { code: 'NF', label: 'Norfolk Island', dial: '+672', flag: '🇳🇫' },
    { code: 'MP', label: 'Northern Mariana Islands', dial: '+1670', flag: '🇲🇵' },
    { code: 'NO', label: 'Norway', dial: '+47', flag: '🇳🇴' },
    { code: 'OM', label: 'Oman', dial: '+968', flag: '🇴🇲' },
    { code: 'PK', label: 'Pakistan', dial: '+92', flag: '🇵🇰' },
    { code: 'PW', label: 'Palau', dial: '+680', flag: '🇵🇼' },
    { code: 'PS', label: 'Palestine', dial: '+970', flag: '🇵🇸' },
    { code: 'PA', label: 'Panama', dial: '+507', flag: '🇵🇦' },
    { code: 'PG', label: 'Papua New Guinea', dial: '+675', flag: '🇵🇬' },
    { code: 'PY', label: 'Paraguay', dial: '+595', flag: '🇵🇾' },
    { code: 'PE', label: 'Peru', dial: '+51', flag: '🇵🇪' },
    { code: 'PH', label: 'Philippines', dial: '+63', flag: '🇵🇭' },
    { code: 'PN', label: 'Pitcairn', dial: '+64', flag: '🇵🇳' },
    { code: 'PL', label: 'Poland', dial: '+48', flag: '🇵🇱' },
    { code: 'PT', label: 'Portugal', dial: '+351', flag: '🇵🇹' },
    { code: 'PR', label: 'Puerto Rico', dial: '+1787', flag: '🇵🇷' },
    { code: 'QA', label: 'Qatar', dial: '+974', flag: '🇶🇦' },
    { code: 'RE', label: 'Réunion', dial: '+262', flag: '🇷🇪' },
    { code: 'RO', label: 'Romania', dial: '+40', flag: '🇷🇴' },
    { code: 'RU', label: 'Russian Federation', dial: '+7', flag: '🇷🇺' },
    { code: 'RW', label: 'Rwanda', dial: '+250', flag: '🇷🇼' },
    { code: 'BL', label: 'Saint Barthélemy', dial: '+590', flag: '🇧🇱' },
    { code: 'SH', label: 'Saint Helena', dial: '+290', flag: '🇸🇭' },
    { code: 'KN', label: 'Saint Kitts and Nevis', dial: '+1869', flag: '🇰🇳' },
    { code: 'LC', label: 'Saint Lucia', dial: '+1758', flag: '🇱🇨' },
    { code: 'MF', label: 'Saint Martin (French part)', dial: '+590', flag: '🇲🇫' },
    { code: 'PM', label: 'Saint Pierre and Miquelon', dial: '+508', flag: '🇵🇲' },
    { code: 'VC', label: 'Saint Vincent and the Grenadines', dial: '+1784', flag: '🇻🇨' },
    { code: 'WS', label: 'Samoa', dial: '+685', flag: '🇼🇸' },
    { code: 'SM', label: 'San Marino', dial: '+378', flag: '🇸🇲' },
    { code: 'ST', label: 'Sao Tome and Principe', dial: '+239', flag: '🇸🇹' },
    { code: 'SA', label: 'Saudi Arabia', dial: '+966', flag: '🇸🇦' },
    { code: 'SN', label: 'Senegal', dial: '+221', flag: '🇸🇳' },
    { code: 'RS', label: 'Serbia', dial: '+381', flag: '🇷🇸' },
    { code: 'SC', label: 'Seychelles', dial: '+248', flag: '🇸🇨' },
    { code: 'SL', label: 'Sierra Leone', dial: '+232', flag: '🇸🇱' },
    { code: 'SG', label: 'Singapore', dial: '+65', flag: '🇸🇬' },
    { code: 'SX', label: 'Sint Maarten (Dutch part)', dial: '+1721', flag: '🇸🇽' },
    { code: 'SK', label: 'Slovakia', dial: '+421', flag: '🇸🇰' },
    { code: 'SI', label: 'Slovenia', dial: '+386', flag: '🇸🇮' },
    { code: 'SB', label: 'Solomon Islands', dial: '+677', flag: '🇸🇧' },
    { code: 'SO', label: 'Somalia', dial: '+252', flag: '🇸🇴' },
    { code: 'ZA', label: 'South Africa', dial: '+27', flag: '🇿🇦' },
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', dial: '+500', flag: '🇬🇸' },
    { code: 'SS', label: 'South Sudan', dial: '+211', flag: '🇸🇸' },
    { code: 'ES', label: 'Spain', dial: '+34', flag: '🇪🇸' },
    { code: 'LK', label: 'Sri Lanka', dial: '+94', flag: '🇱🇰' },
    { code: 'SD', label: 'Sudan', dial: '+249', flag: '🇸🇩' },
    { code: 'SR', label: 'Suriname', dial: '+597', flag: '🇸🇷' },
    { code: 'SJ', label: 'Svalbard and Jan Mayen', dial: '+47', flag: '🇸🇯' },
    { code: 'SZ', label: 'Swaziland', dial: '+268', flag: '🇸🇿' },
    { code: 'SE', label: 'Sweden', dial: '+46', flag: '🇸🇪' },
    { code: 'CH', label: 'Switzerland', dial: '+41', flag: '🇨🇭' },
    { code: 'SY', label: 'Syrian Arab Republic', dial: '+963', flag: '🇸🇾' },
    { code: 'TW', label: 'Taiwan', dial: '+886', flag: '🇹🇼' },
    { code: 'TJ', label: 'Tajikistan', dial: '+992', flag: '🇹🇯' },
    { code: 'TZ', label: 'Tanzania', dial: '+255', flag: '🇹🇿' },
    { code: 'TH', label: 'Thailand', dial: '+66', flag: '🇹🇭' },
    { code: 'TL', label: 'Timor-Leste', dial: '+670', flag: '🇹🇱' },
    { code: 'TG', label: 'Togo', dial: '+228', flag: '🇹🇬' },
    { code: 'TK', label: 'Tokelau', dial: '+690', flag: '🇹🇰' },
    { code: 'TO', label: 'Tonga', dial: '+676', flag: '🇹🇴' },
    { code: 'TT', label: 'Trinidad and Tobago', dial: '+1868', flag: '🇹🇹' },
    { code: 'TN', label: 'Tunisia', dial: '+216', flag: '🇹🇳' },
    { code: 'TR', label: 'Turkey', dial: '+90', flag: '🇹🇷' },
    { code: 'TM', label: 'Turkmenistan', dial: '+993', flag: '🇹🇲' },
    { code: 'TC', label: 'Turks and Caicos Islands', dial: '+1649', flag: '🇹🇨' },
    { code: 'TV', label: 'Tuvalu', dial: '+688', flag: '🇹🇻' },
    { code: 'UG', label: 'Uganda', dial: '+256', flag: '🇺🇬' },
    { code: 'UA', label: 'Ukraine', dial: '+380', flag: '🇺🇦' },
    { code: 'AE', label: 'United Arab Emirates', dial: '+971', flag: '🇦🇪' },
    { code: 'GB', label: 'United Kingdom', dial: '+44', flag: '🇬🇧' },
    { code: 'US', label: 'United States', dial: '+1', flag: '🇺🇸' },
    { code: 'UM', label: 'United States Minor Outlying Islands', dial: '+1', flag: '🇺🇲' },
    { code: 'UY', label: 'Uruguay', dial: '+598', flag: '🇺🇾' },
    { code: 'UZ', label: 'Uzbekistan', dial: '+998', flag: '🇺🇿' },
    { code: 'VU', label: 'Vanuatu', dial: '+678', flag: '🇻🇺' },
    { code: 'VE', label: 'Venezuela', dial: '+58', flag: '🇻🇪' },
    { code: 'VN', label: 'Vietnam', dial: '+84', flag: '🇻🇳' },
    { code: 'VG', label: 'Virgin Islands, British', dial: '+1284', flag: '🇻🇬' },
    { code: 'VI', label: 'Virgin Islands, U.S.', dial: '+1340', flag: '🇻🇮' },
    { code: 'WF', label: 'Wallis and Futuna', dial: '+681', flag: '🇼🇫' },
    { code: 'EH', label: 'Western Sahara', dial: '+212', flag: '🇪🇭' },
    { code: 'YE', label: 'Yemen', dial: '+967', flag: '🇾🇪' },
    { code: 'ZM', label: 'Zambia', dial: '+260', flag: '🇿🇲' },
    { code: 'ZW', label: 'Zimbabwe', dial: '+263', flag: '🇿🇼' }
];
